#!/usr/bin/env python3
"""Focused synthetic capacity tests for Voyager production packaging."""

from collections import Counter
from pathlib import Path
import sys
import tempfile
import unittest
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parent))

from voyager_packaging import (
    AREA_MAX_TRACKS,
    AREA_TRACK_SLOT_HEADROOM,
    Component,
    Edge,
    PermanentCapacityError,
    Point,
    SourceGraph,
    Step,
    Walk,
    MAX_TRACKS,
    allocate_pools,
    build_area_pack,
    output_sequences,
    write_area_gpx,
)


def synthetic_walks(point_counts: list[int]) -> tuple[list[Walk], list[Edge]]:
    walks: list[Walk] = []
    edges: list[Edge] = []
    next_node = 0
    for component_id, point_count in enumerate(point_counts):
        if point_count < 2:
            raise ValueError("Synthetic walks need at least two points.")
        steps: list[Step] = []
        for _ in range(point_count - 1):
            edge_id = len(edges)
            edges.append(Edge(edge_id, next_node, next_node + 1, "source", edge_id))
            steps.append(Step(edge_id, next_node, next_node + 1))
            next_node += 1
        next_node += 1
        walks.append(Walk(component_id, tuple(steps)))
    return walks, edges


def traversal_ids(walks: tuple[Walk, ...]) -> Counter[int]:
    return Counter(step.edge_id for walk in walks for step in walk.steps)


class VoyagerCapacityTests(unittest.TestCase):
    def test_area_packs_preserve_ten_track_slots(self) -> None:
        self.assertEqual(AREA_TRACK_SLOT_HEADROOM, 10)
        self.assertEqual(AREA_MAX_TRACKS, MAX_TRACKS - 10)

    def test_output_gpx_contains_only_device_geometry_and_path_names(self) -> None:
        walks, edges = synthetic_walks([3, 2])
        allocation = allocate_pools(walks, edges)
        nodes = tuple(
            Point(str(45 + index / 1000), str(-123 + index / 1000))
            for index in range(5)
        )
        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary) / "clean.gpx"
            write_area_gpx(output, "CL00001", allocation, nodes)
            text = output.read_text(encoding="utf-8")
            for marker in ("<metadata", "<desc", "<cmt", "<!--", "Codex", "OpenAI"):
                self.assertNotIn(marker, text)
            counts, routes, tracks = output_sequences(output)
            self.assertEqual(counts["waypointCount"], 0)
            self.assertEqual(len(routes), 0)
            self.assertEqual(len(tracks), 2)

    def test_editorial_metadata_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary) / "annotated.gpx"
            output.write_text(
                '<?xml version="1.0" encoding="utf-8"?>'
                '<gpx xmlns="http://www.topografix.com/GPX/1/1" version="1.1" '
                'creator="Bob\'s Motorcycle Trails"><metadata><desc>Generated by AI'
                '</desc></metadata></gpx>',
                encoding="utf-8",
            )
            with self.assertRaisesRegex(RuntimeError, "editorial or internal metadata"):
                output_sequences(output)

    def test_small_pack_prefers_tracks(self) -> None:
        walks, edges = synthetic_walks([100, 80, 60])
        allocation = allocate_pools(walks, edges)
        self.assertEqual(len(allocation.tracks), 3)
        self.assertEqual(len(allocation.routes), 0)

    def test_point_capacity_moves_path_to_route_below_track_count_limit(self) -> None:
        walks, edges = synthetic_walks([40_000, 40_000])
        allocation = allocate_pools(walks, edges)
        self.assertEqual(len(allocation.tracks), 1)
        self.assertEqual(len(allocation.routes), 1)
        self.assertEqual(allocation.track_point_count, 40_000)
        self.assertEqual(allocation.route_point_count, 40_000)
        self.assertEqual(
            traversal_ids(allocation.tracks + allocation.routes),
            Counter(range(len(edges))),
        )

    def test_overlong_walk_splits_only_at_existing_vertex(self) -> None:
        walks, edges = synthetic_walks([80_000])
        allocation = allocate_pools(walks, edges)
        output_walks = allocation.tracks + allocation.routes
        self.assertEqual(len(output_walks), 2)
        self.assertEqual(len(allocation.tracks), 1)
        self.assertEqual(len(allocation.routes), 1)
        self.assertEqual(
            allocation.track_point_count + allocation.route_point_count,
            80_001,
        )
        self.assertEqual(
            traversal_ids(output_walks),
            Counter(range(len(edges))),
        )
        endpoints = [
            (walk.steps[0].start, walk.steps[-1].end) for walk in output_walks
        ]
        self.assertEqual(endpoints[0][1], endpoints[1][0])

    def test_more_than_590_components_is_explicit_permanent_failure(self) -> None:
        graph = SourceGraph(
            nodes=(),
            source_edges=(),
            source_segments=(),
            source_files=(),
            adjacency=(),
            representative_edge={},
            components=tuple(
                Component(index, (), (), ()) for index in range(591)
            ),
        )
        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary) / "impossible.gpx"
            with patch("voyager_packaging.load_source_graph", return_value=graph):
                with self.assertRaisesRegex(
                    PermanentCapacityError, "disconnected components"
                ):
                    build_area_pack(
                        database=Path(temporary),
                        target_id="too-many-components",
                        target_name="Too Many Components",
                        target_kind="synthetic",
                        device_code="TM00001",
                        catalog=[],
                        output_path=output,
                    )


if __name__ == "__main__":
    unittest.main()
